name: VS Code Extension CI

on:
  push:
    branches: [ main ]
    paths:
      - 'packages/extension/**'
      - '.github/workflows/extension-ci.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'packages/extension/**'
      - '.github/workflows/extension-ci.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18
        cache: 'npm'
    
    - name: Install dependencies
      run: |
        cd packages/extension
        npm install
    
    - name: Lint
      run: |
        cd packages/extension
        npm run lint
    
    - name: Run tests
      run: |
        cd packages/extension
        npm test
    
    - name: Build
      run: |
        cd packages/extension
        npm run package
    
    - name: Package VSIX
      run: |
        cd packages/extension
        npx @vscode/vsce package
    
    - name: Upload VSIX
      uses: actions/upload-artifact@v3
      with:
        name: pincast-expo-extension
        path: packages/extension/*.vsix
        
    - name: Create Release
      if: github.ref == 'refs/heads/main'
      uses: softprops/action-gh-release@v1
      with:
        files: packages/extension/*.vsix
        tag_name: extension-v${{ github.run_number }}
        name: Pincast Expo Extension v0.2.${{ github.run_number }}
        draft: true
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}